### ISSUE TITLE
Error converting a string of characters in date and / or time

### ISSUE THREAD

**Issue by youchun83** [minagerges/AutoPatcher#13] opened 2018-03-06 05:17 UTC
When I run Autopatcher, I get an Error (a string of characters in date and / or time)
The reason for this error is that the time format AM / PM on the server.

Must change the time to 24H.
Control Panel -> Region -> short time = HHmm, Long time = HH: mm: ss.

**Comment by minagerges** [comment] 2018-03-06 12:01
Not reproducible. I have time set to 12hours format (AM/PM), and it is working as expected.
Can you please provide the full error message and system locate information!

**Comment by youchun83** [comment] 2018-03-07 00:38
The error log is copied below.
Perhaps my Altiris installed on Korean OS so AM / PM does not come out in the 오전 / 오후?

AutoPatcher operation initiated!
Loading all Bulletins details...
System.Data.SqlClient.SqlException: 문자열을 날짜 및/또는 시간으로 변환하지 못했습니다.
AllBulletinsDetailsLoaded received empty DataTable!
Loaded (0) Bulletins details, in 00:00:07.8084643
Selected 0 Bulletins with criteria: Platform = 'Any' AND ReleaseDate >= '2017-10-01 오전 12:00:00' AND Superseded <> 'Yes'  AND Applicable >= 1  AND DisabledByUser = 0 AND Policies = 0  
Applied Bulletins filter did not return any results! Operation cancelled.


Error #1

System.Data.SqlClient.SqlException: 문자열을 날짜 및/또는 시간으로 변환하지 못했습니다.
-----------------------------------------------------------------------------------------------------
Date: 2018-03-07 오전 09:34:11, Tick Count: 140236234 (1.14:57:16.2340000), Host Name: CYBERADAPTBMT, Size: 359 B
Process: AutoPatcher (15800), Thread ID: 29, Module: AutoPatcher.exe
Priority: 1, Source: AutoPatcher.Common::SQLHelper.RunQuery
File: C:\ProgramData\Symantec\SMP\Logs\a.log

Error #2
Failed to run SQL query on SMP DataBase.

문자열을 날짜 및/또는 시간으로 변환하지 못했습니다.
   [System.Data.SqlClient.SqlException @ .Net SqlClient Data Provider]
   위치: System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   위치: System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   위치: System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   위치: System.Data.SqlClient.SqlDataReader.TryHasMoreRows(Boolean& moreRows)
   위치: System.Data.SqlClient.SqlDataReader.TryReadInternal(Boolean setTimeout, Boolean& more)
   위치: System.Data.SqlClient.SqlDataReader.Read()
   위치: System.Data.Common.DataAdapter.FillLoadDataRow(SchemaMapping mapping)
   위치: System.Data.Common.DataAdapter.FillFromReader(DataSet dataset, DataTable datatable, String srcTable, DataReaderContainer dataReader, Int32 startRecord, Int32 maxRecords, DataColumn parentChapterColumn, Object parentChapterValue)
   위치: System.Data.Common.DataAdapter.Fill(DataTable[] dataTables, IDataReader dataReader, Int32 startRecord, Int32 maxRecords)
   위치: System.Data.DataTable.Load(IDataReader reader, LoadOption loadOption, FillErrorEventHandler errorHandler)
   위치: AutoPatcher.Common.SQLHelper.RunQuery(String Query)

SQL Exception details: code=241, line=158

Exception logged from: 
   at AutoPatcher.Common.SQLHelper.RunQuery(String)
   at AutoPatcher.Common.SQLHelper.RunQuery(String, TimeSpan&)
   at AutoPatcher.Operation.AutoPatcherOperations.GetAllBulletinsDetails(System.DateTime, Boolean)
   at AutoPatcher.Operation.AutoPatcherOperations.GetAllBulletinsDetailsByPlatform(System.DateTime, AutoPatcher.Operation.AutoPatcherConfig+Constants+Platform)
   at AutoPatcher.Operation.AutoPatcherOperations.FilterDistributableBulletins(AutoPatcher.Operation.AutoPatcherConfig, Boolean, Boolean)
   at AutoPatcher.Operation.AutoPatcherOperations.DoRun(AutoPatcher.Operation.AutoPatcherConfig)
   at AutoPatcher.Operation.AutoPatcherOperations.Run(AutoPatcher.Operation.AutoPatcherConfig, Boolean)
   at AutoPatcher.UI.FormMain+<>c__DisplayClass45.<Run_Click>b__41()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, Object)
   at System.Threading.ThreadHelper.ThreadStart()

User [CYBERADAPTBMT\symantecSMP], Auth [CYBERADAPTBMT\symantecSMP], AppDomain [AutoPatcher.exe]

-----------------------------------------------------------------------------------------------------
Date: 2018-03-07 오전 09:34:11, Tick Count: 140236234 (1.14:57:16.2340000), Host Name: CYBERADAPTBMT, Size: 3.14 KB
Process: AutoPatcher (15800), Thread ID: 29, Module: AutoPatcher.exe
Priority: 1, Source: AutoPatcher.Common.SQLHelper.RunQuery
File: C:\ProgramData\Symantec\SMP\Logs\a.log

**Comment by minagerges** [comment] 2018-03-07 09:37
Thanks for the details. I identified the cause.
Fix will be included in next release.

**Comment by minagerges** [comment] 2018-03-07 11:34
Fixed in [8.0.6640.21880](https://github.com/minagerges/AutoPatcher/releases/tag/8.0.6640.21880)

**Closed as completed by minagerges** 2018-03-07 11:34 UTC
Labels: bug, enhancement
